#-------------------------------
# General Site Settings
# 	include using {{ site.data.settings.<variable> }}

title: MSUM ACM
description: >
  Full description of the organization

email: msumacm.org@gmail.com
address: 1104 7th Ave South, Moorhead, MN 56563 USA
location: Bridges 163
#phone: xxx-xxx-xxxx

#-------------------------------
# Desgin and Copy Right Messages

copyright: '&copy; 2015 MSUM ACM organization, all rights reserved.Hosted by GitHub.'
Desginby: 'Designed and developed by Jake Humphrey and Anthony Ferre.'
designMeta: 
  specialThanks: 'Special thank you to Ben Jyring for designing the MSUM ACM logo.'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

#google-analytics-ua: UA-XXXXXX-X
