#-------------------------------
# General Site Settings
# 	include using {{ site.data.settings.<variable> }}

title: MSUM ACM
description: >
  Full description of the organization

email: emailforclub@something.com

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

#google-analytics-ua: UA-XXXXXX-X